#ifndef DEFAULT_POSITIONS_H_
#define DEFAULT_POSITIONS_H_

#include "joint_indices.h"

#define NECK_YAW_DEFAULT_POS 0.0
#define NECK_PITCH_DEFAULT_POS 0.0

#define LEFT_SHOULDER_PITCH_DEFAULT_POS 0.0
#define LEFT_SHOULDER_ROLL_DEFAULT_POS 0.0
#define LEFT_ELBOW_DEFAULT_POS 0.0

#define RIGHT_SHOULDER_PITCH_DEFAULT_POS 0.0
#define RIGHT_SHOULDER_ROLL_DEFAULT_POS 0.0
#define RIGHT_ELBOW_DEFAULT_POS 0.0

#define LEFT_HIP_YAW_DEFAULT_POS 0.0
#define LEFT_HIP_ROLL_DEFAULT_POS 0.0
#define LEFT_HIP_PITCH_DEFAULT_POS 15.0
#define LEFT_KNEE_DEFAULT_POS 5.0
#define LEFT_ANKLE_PITCH_DEFAULT_POS -5.0
#define LEFT_ANKLE_ROLL_DEFAULT_POS 0.0

#define RIGHT_HIP_YAW_DEFAULT_POS 0.0
#define RIGHT_HIP_ROLL_DEFAULT_POS 0.0
#define RIGHT_HIP_PITCH_DEFAULT_POS -15.0
#define RIGHT_KNEE_DEFAULT_POS -5.0
#define RIGHT_ANKLE_PITCH_DEFAULT_POS 5.0
#define RIGHT_ANKLE_ROLL_DEFAULT_POS 0.0

const float standing_positions[NUM_POWERED_JOINTS]  = {
NECK_YAW_DEFAULT_POS , 
NECK_PITCH_DEFAULT_POS ,
LEFT_SHOULDER_PITCH_DEFAULT_POS ,
LEFT_SHOULDER_ROLL_DEFAULT_POS ,
LEFT_ELBOW_DEFAULT_POS ,
RIGHT_SHOULDER_PITCH_DEFAULT_POS ,
RIGHT_SHOULDER_ROLL_DEFAULT_POS ,
RIGHT_ELBOW_DEFAULT_POS ,

LEFT_HIP_YAW_DEFAULT_POS ,
LEFT_HIP_ROLL_DEFAULT_POS ,
LEFT_HIP_PITCH_DEFAULT_POS ,
LEFT_KNEE_DEFAULT_POS ,
LEFT_ANKLE_PITCH_DEFAULT_POS ,
LEFT_ANKLE_ROLL_DEFAULT_POS ,

RIGHT_HIP_YAW_DEFAULT_POS ,
RIGHT_HIP_ROLL_DEFAULT_POS ,
RIGHT_HIP_PITCH_DEFAULT_POS ,
RIGHT_KNEE_DEFAULT_POS ,
RIGHT_ANKLE_PITCH_DEFAULT_POS ,
RIGHT_ANKLE_ROLL_DEFAULT_POS
};

#endif